name: release

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - "!.github/**"
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Prepare
        run: make promu

      - name: Test and build
        run: make

      - name: Build tarballs
        run: promu crossbuild tarballs

      - name: Checksum tarballs
        run: promu checksum .tarballs

      - name: Release tarballs
        run: promu release .tarballs

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: .build/
