name: Org Repository Banner Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  generate:
    permissions:
      contents: write
    uses: angarium-cloud/.github/.github/workflows/repo-banner.yml@main
